import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/providers/AuthProvider";
import 'react-toastify/dist/ReactToastify.css';
import ReactQueryProvider from "./providers/Reactquery/QueryProvider";
import Head from "@/components/Head/Head";
import { StorageProvider } from "./providers/context/userInfo";

const roboto = Roboto({  
  subsets: ['latin'],  
  weight: ['400'] 
}); 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  dir="rtl">
      <body
        className={` ${roboto.className} antialiased `}
      >
        <StorageProvider>
        <ReactQueryProvider>
        <AuthProvider>
          <Head />
        {children}
        </AuthProvider>
        </ReactQueryProvider>
        </StorageProvider>
      </body>
    </html>
  );
}
